DATA_DIR: '../data'
OUTPUT_DIR: '../models'
DATASET:
  DATA_FORMAT: csv
  PREPROCESSING:
    MERGE_FILES:
      WHICH: "all"  # Either "all" or list of indexes. ex : [2] or [0, 1, 2] or [2, 0] ...
    NORMALIZE:
      TYPE: "StandardScaler"  # ["MinMaxScalar", "StandardScaler"]
    REMOVE_FEATURES:
      ACTIVE: True
      WHICH: ["Linespeed (m/min)", "B ppm"]
    REMOVE_SAMPLES:
      ACTIVE: False
      WHICH:
        #Direction: "T"  # ["T", "L"]
        Type: "JI5"  # ["JI5", "I20"]

    TARGET: "rm"  # ["rm", "re02", "A80"]
  BATCH_SIZE: 32
  TEST_VALID_RATIO: [0.1, 0.2]
  VERBOSITY: True
  NUM_THREADS: 4
MODELS:
  NN: True
  ML:
    ACTIVE: True
    GRID_SEARCH: False
    TYPE: 'GradientBoosting'  # ["RandomForest", ExtraTrees, GradientBoosting]
    RandomForest:
      rm:
        bootstrap: False
        max_depth: 21
        max_features: 10
        min_samples_split: 6
        n_estimators: 100
        n_jobs: -1
      re02:
        bootstrap: False
        max_depth: 26
        max_features: 10
        min_samples_split: 6
        n_estimators: 110
        n_jobs: -1
      A80:
        bootstrap: False
        max_depth: 25
        max_features: 11
        min_samples_split: 4
        n_estimators: 105
        n_jobs: -1
    ExtraTrees:
      rm:
        bootstrap: False
        max_depth: 23
        max_features: 11
        min_samples_split: 6
        n_estimators: 105
        n_jobs: -1
      re02:
        bootstrap: False
        max_depth: 23
        max_features: 11
        min_samples_split: 6
        n_estimators: 110
        n_jobs: -1
      A80:
        bootstrap: False
        max_depth: 21
        max_features: 10
        min_samples_split: 6
        n_estimators: 70
        n_jobs: -1
    GradientBoosting:
      rm:
        max_depth: 23
        max_features: 11
        min_samples_split: 6
        n_estimators: 110
      re02:
        max_depth: 23
        max_features: 11
        min_samples_split: 6
        n_estimators: 110
      A80:
        max_depth: 21
        max_features: 10
        min_samples_split: 6
        n_estimators: 70
TRAIN:
  EPOCH: 100
  CHECKPOINT_STEP: 500
  MODEL: LinearNet_3
  NUM_HIDDEN_NEURON: 64
  LOG_DIR: 'tensorboard/metrics'
  SAVE_DIR: '../models'
  LR:
    LR_INITIAL : 0.01
    TYPE: "ReduceLROnPlateau"  # [ReduceLROnPlateau, CyclicLR]
    ReduceLROnPlateau:
      LR_DECAY: 0.2
      LR_PATIENCE : 10
      LR_THRESHOLD : 1
    CyclicLR:
      BASE_LR: 0.00001
      MAX_LR: 0.001
      STEP_SIZE: 500
TEST:
  BATCH_SIZE: 16
  SAVE_DIR: '../res'
  PATH_TO_MODEL: '../models/linearnet_3_0/best_model.pth'
  AVERAGE:
    ACTIVE: True
    PATH:
      - {MODEL: '../models/randomforest_23/model.pck', CONFIG: '../models/randomforest_23/config_file.yaml'}
      - {MODEL: '../models/gradientboosting_26/model.pck', CONFIG: '../models/gradientboosting_26/config_file.yaml'}
      - {MODEL: '../models/extratrees_23/model.pck', CONFIG: '../models/extratrees_23/config_file.yaml'}
