DATA_DIR: '../data'
OUTPUT_DIR: '../models'
DATASET:
  DATA_FORMAT: csv
  PREPROCESSING:
    MERGE_FILES:
      WHICH: "all"  # Either "all" or list of indexes. ex : [2] or [0, 1, 2] or [2, 0] ...
    NORMALIZE:
      TYPE: "StandardScaler"  # ["MinMaxScalar", "StandardScaler"]
    REMOVE_FEATURES:
      ACTIVE: True
      WHICH: ["Linespeed (m/min)", "B ppm"]
    REMOVE_SAMPLES:
      ACTIVE: True
      WHICH:
        #Direction: "T"  # ["T", "L"]
        Type: "JI5"  # ["JI5", "I20"]

    TARGET: "rm"  # ["rm", "re02", "A80"]
  BATCH_SIZE: 32
  TEST_VALID_RATIO: [0.1, 0.2]
  VERBOSITY: True
  NUM_THREADS: 4
MODELS:
  NN: True
  ML:
    ACTIVE: True
    GRID_SEARCH: False
    TYPE: 'RandomForest'  # ["RandomForest" ...]
    RandomForest:
      rm:
        bootstrap: False
        max_depth: 21
        max_features: 10
        min_samples_split: 6
        n_estimators: 100
        n_jobs: -1
      re02:
        bootstrap: False
        max_depth: 26
        max_features: 10
        min_samples_split: 6
        n_estimators: 110
        n_jobs: -1
      A80:
        bootstrap: False
        max_depth: 25
        max_features: 11
        min_samples_split: 4
        n_estimators: 105
        n_jobs: -1
TRAIN:
  EPOCH: 2
  CHECKPOINT_STEP: 500
  MODEL: LinearNet_2
  NUM_HIDDEN_NEURON: 50
  LOG_DIR: 'tensorboard/metrics'
  SAVE_DIR: '../models'
  LR:
    LR_INITIAL : 0.001
    TYPE: "CyclicLR"  # [ReduceLROnPlateau, CyclicLR]
    ReduceLROnPlateau:
      LR_DECAY: 0.01
      LR_PATIENCE : 3
      LR_THRESHOLD : 0.02
    CyclicLR:
      BASE_LR: 0.00001
      MAX_LR: 0.001
      STEP_SIZE: 500
TEST:
  BATCH_SIZE: 16
